### ISSUE TITLE
Gives the ability to use another port for PubSub

### ISSUE THREAD

**Issue by FPierre** [NeoScript/pubsub-emulator-ui#13]
It is not [possible yet](https://github.com/NeoScript/pubsub-emulator-ui/blob/main/webapp/src/app/services/pubsub.service.ts#L11) to use another port for PubSub (not configurable).

I've the following docker-compose:
```yaml
pubsub:
  image: 'google/cloud-sdk'
  command: 'gcloud beta emulators pubsub start --host-port=0.0.0.0:8085'
  ports:
    - '8085:8085'

pubsub-dashboard:
  image: ghcr.io/neoscript/pubsub-emulator-ui:latest
  ports:
    - '8086:80'
 ```

that expose PubSub on port `8085` which makes it impossible to use the UI
