### ISSUE TITLE
feature: add possibility to pre-provision projects to Docker Container env

### ISSUE THREAD

**Issue by msrokowski** [NeoScript/pubsub-emulator-ui#20]
Similar to `echocode-io/gcp-pubsub-emulator-ui` project please add possibility to predefine projects on container build, ie.:

```yaml
version: "3.9"

services:
  pubsub_emulator:
    image: messagebird/gcloud-pubsub-emulator:latest
    ports:
      - "8681:8681"
    environment:
      - PUBSUB_PROJECT1=test-project,topic1:topic1-sub,topic2:t2-s1:t2-s2

  emulator-ui:
    image: ghcr.io/neoscript/pubsub-emulator-ui:latest
    ports:
      - "7200:80"
    environment:
      - PUBSUB_PROJECTS=test-project
```
