### ISSUE TITLE
docker-compose options

### ISSUE THREAD

**Issue by LegendSebastianoL** [NeoScript/pubsub-emulator-ui#25]
hey 👋 

I have a docker-compose that spin up everything, just a bit different from your example

```yaml
  # PubSub
  pubsub:
    image: google/cloud-sdk:emulators
    container_name: pubsub
    command: bash -c "gcloud beta emulators pubsub start --project=some-project-id --host-port='0.0.0.0:8085'"
    volumes: 
      - pubsub_data:/opt/data
    ports:
      - "8085:8085"
    networks:
      - app-network
```

- is there a way to specify the port where the PubSub is running in this emulator UI? 
- is there a volume I can attach to it and name it? like I did in the `cloud-sdk` image
